/**
 * deploy.js
 * ─────────
 * Deploys StakingPlatform.sol and writes the deployed address + ABI into
 * client/src/contractConfig.js so the React frontend picks it up automatically.
 *
 * Usage:
 *   npx hardhat run scripts/deploy.js --network localhost
 *   npx hardhat run scripts/deploy.js --network sepolia
 */

const { ethers } = require("hardhat");
const fs   = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();

  console.log("=".repeat(60));
  console.log("CN6035 – StakingPlatform Deployment");
  console.log("=".repeat(60));
  console.log(`Network     : ${hre.network.name}`);
  console.log(`Deployer    : ${deployer.address}`);
  console.log(
    `Balance     : ${ethers.formatEther(
      await ethers.provider.getBalance(deployer.address)
    )} ETH`
  );
  console.log("-".repeat(60));

  // ── 1. Deploy the contract ────────────────────────────────────────────────
  const StakingPlatform = await ethers.getContractFactory("StakingPlatform");
  const contract = await StakingPlatform.deploy();
  await contract.waitForDeployment();

  const contractAddress = await contract.getAddress();
  console.log(`Contract deployed at : ${contractAddress}`);

  // ── 2. Fund the contract with some ETH to cover reward pay-outs ──────────
  //    In production you would fund this separately; here we seed 0.5 ETH.
  const fundTx = await deployer.sendTransaction({
    to: contractAddress,
    value: ethers.parseEther("0.01"),
  });
  await fundTx.wait();
  console.log(`Reward pool funded   : 0.01 ETH`);

  // ── 3. Write contractConfig.js for the React frontend ────────────────────
  const artifactPath = path.join(
    __dirname,
    "..",
    "artifacts",
    "contracts",
    "StakingPlatform.sol",
    "StakingPlatform.json"
  );

  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));

  const configContent = `// AUTO-GENERATED by scripts/deploy.js – do not edit manually
// Re-run the deploy script to update after redeployment.

export const CONTRACT_ADDRESS = "${contractAddress}";

export const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};
`;

  const clientConfigPath = path.join(
    __dirname,
    "..",
    "client",
    "src",
    "contractConfig.js"
  );

  fs.writeFileSync(clientConfigPath, configContent);
  console.log(`contractConfig.js written → ${clientConfigPath}`);

  console.log("=".repeat(60));
  console.log("Deployment complete!");
  console.log("=".repeat(60));
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
